development:
  bucket: ENV['AWS_BUCKET_DEVELOPMENT']
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_KEY']
  s3_access: public_read

test:
  bucket: ENV['AWS_BUCKET_TEST']
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_KEY']
  use_ssl: true
  s3_access: authenticated_read

production:
  bucket: ENV['AWS_BUCKET_PRODUCTION']
  access_key_id: ENV['AWS_ACCESS_KEY']
  secret_access_key: ENV['AWS_SECRET_KEY']
  use_ssl: true
  s3_access: authenticated_read
